echo "version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cinnamon_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
" > docker-compose.yml
